Oaxaca/Oaxaca/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('restaurant.urls')),
]

Oaxaca/restaurant/urls.py
from django.urls import path
from . import views

app_name = "restaurant"  


urlpatterns = [
    path("about/", views.about, name="about"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("accounts/login/", views.login_request, name="login"),
    path('pay/<int:id>', views.payment, name='pay'),
    path('pay/<int:id>/success/', views.payment_success, name='pay_success'),
    path('manage/menu/', views.staff_menu, name='staff-menu'),
    path('manage/menu/edit/<int:id>',
         views.staff_dish_details, name='staff-dish-details'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('orders/<int:customer_id>', views.orders, name='orders'),
    path('', views.index, name='index'),
    path('logout/', views.logout_request, name='logout'),
    path('tableManager/', views.tableManager, name="tableManager"),
    path('update_table/<str:pk>/', views.updateTable, name="update_table"),
]

Oaxaca/users/urls.py
from django.contrib import admin
from django.urls import include, path
from users.views import DashboardWaiter

urlpatterns = [
    path('dashboard_waiter/', DashboardWaiter.as_view(), name='dashboard_waiter'),
]

Oaxaca/restaurant/models.py
from django.db import models
from array import array
from django.contrib.auth.models import User
# Create your models here.


# Allergies table
class Allergies(models.Model):
    allergies_id = models.AutoField(primary_key=True)
    allergies_name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.allergies_name)
        return str(self.allergies_name)


# Ingredients table
class Ingredient(models.Model):
    ingredient_id = models.AutoField(primary_key=True)
    allergies_id = models.ManyToManyField(Allergies)
    ingredient_name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.ingredient_name)
        return str(self.ingredient_name)


# Category table
class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.category_name)


# Dish table
class Dish(models.Model):
    dish_id = models.AutoField(primary_key=True)
    dish_name = models.CharField(max_length=75)
    dish_quantity = models.IntegerField()
    dish_price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_calories = models.IntegerField()
    dish_availability = models.BooleanField(default=False)

    ingredient_id = models.ManyToManyField(Ingredient)
    category_id = models.ManyToManyField(Category)

    def __str__(self):
        return str(self.dish_name)


# Customer table
class Customer(models.Model):
    table_id = models.AutoField(primary_key = True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=11, decimal_places=2)
    persons = models.IntegerField()
    maxpersons = models.IntegerField(default=0)
    need_help = models.BooleanField(default=False)

    def __str__(self):
        return str(self.table_id)

 
# Status table
class Status(models.Model):
    class Statuses(models.TextChoices):
        InProgress = 'Order in progress'
        Received = 'Received'
        Cooking = 'Cooking'
        Ready = 'Ready to serve'
        Delivered = 'Delivered'
        Problem = 'Problem'
        Cancelled = 'Cancelled'

    status_id = models.AutoField(primary_key=True)
    status_name = models.CharField(
        max_length=20, choices=Statuses.choices, default=Statuses.InProgress)

    def __str__(self):
        return str(self.status_name)


# Order table
class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_time = models.DateTimeField()
    table_id = models.IntegerField()
    customer = models.ForeignKey(Customer, null=True, to_field='user', on_delete=models.CASCADE)
    order_finish = models.BooleanField(default = False)
    dish_id = models.ManyToManyField(Dish)
    status_id = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return "Order no: " + str(self.order_id)
    
class Payment(models.Model):
    payment_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField()
    payment_time = models.DateTimeField()
    payment_amount = models.DecimalField(max_digits=7, decimal_places=2)
     
    def __str__(self):
        return "Order no: " + str(self.order_id) + "Amount: " + str(self.payment_amount)

Oaxaca/restaurant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Dish, Order, Customer


# Create your forms here.

class CreateNewUser(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(CreateNewUser, self).save(commit=False)
        if commit:
            user.save()
        return user


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ['dish_name', 'dish_quantity', 'dish_price',
                  'dish_calories', 'dish_availability']
        widgets = {
            'dish_name': forms.TextInput(attrs={'class': 'table-cell'}),
            'dish_quantity': forms.NumberInput(attrs={'class': 'table-cell'}),
            'dish_price': forms.NumberInput(attrs={'class': 'table-cell'}),
            'dish_calories': forms.NumberInput(attrs={'class': 'table-cell'}),
            'dish_availability': forms.CheckboxInput(attrs={'class': 'slide-toggle-checkbox'}),
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['order_time', 'order_id', 'dish_id', 'status_id']
        
class TableForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['table_id', 'user', 'total_price', 'persons', 'need_help',]
       
        widgets = {
            'table_id': forms.TextInput(attrs={'class': 'table-cell'}),
            'user': forms.Select(attrs={'class': 'table-cell'}),
            'total_price': forms.NumberInput(attrs={'class': 'table-cell'}),
            'persons': forms.Select(choices=[(1,1)],attrs={'class': 'table-cell'}),
            'need_help': forms.CheckboxInput(attrs={'class': 'form-control-input'}),
        }
    
    def __init__(self, *args, **kwargs):
        maxpersons = kwargs.pop('maxpersons')
        super().__init__(*args, **kwargs)
        numpersons = [(people, people) for people in range(0, maxpersons+1)]
        self.fields['persons'].widget.choices =numpersons

Oaxaca/restaurant/views.py
from collections import defaultdict
from datetime import datetime
from decimal import Decimal
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .forms import CreateNewUser, DishForm, OrderForm, TableForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.contrib.auth import logout
from django.template import loader
from django.template.loader import render_to_string
from restaurant.models import *


def redirect_request(request):
    return render(request=request, template_name="restaurant/menu_public.html")


def register_request(request): 
    if request.method == "POST": # Checks if request method is secure POST
        form = CreateNewUser(request.POST)
        if form.is_valid(): # Checks if details entered match requirements
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("restaurant:login") # Redirects user to the login page
        messages.error(
            request, "Unsuccessful registration. Invalid information.") # If details failed to pass requirements, returns this message.
    form = CreateNewUser()
    return render(request=request, template_name="restaurant/register.html", context={"register_form": form})


def logout_request(request):
    logout(request) 
    return render(request=request, template_name="restaurant/logout.html") # Logs user out on button press and temporarily holds them 
                                                                           # at a redirect page.
def autosearch(request):
    if 'term' in request.GET:
        data = []
        query_set = Dish.objects.filter(
            dish_name__icontains=request.GET.get('term')).order_by('dish_name')
        for result in query_set:
            data = [{'name': result.dish_name}]
        return JsonResponse({'data': data})



def index(request):
    """Builds the index (menu) using dish data from the database and renders to browser.

    Args:
        request (HttpRequest): Object containing metadata about the request

    Returns:
        HttpResponse: a rendered HTML page using index template and dish data
    """

    # Get allergen information from DB ordered by allergies_id
    allergens = Allergies.objects.all().order_by('allergies_id').values()

    # Get dish categories from DB
    dish_categories = Category.objects.values()

    # Get all dishes from DB ordered by dish name
    dish_all = Dish.objects.all().order_by('dish_name')

    # Create a dictionary of lists to store dishes based on category
    dish_by_categories = defaultdict(list)
    dish_by_categories.default_factory = None
    # Pre-fill categories to dictionary
    for category in dish_categories:
        dish_by_categories[category['category_name']] = []

    # Create list for filtering with JS
    dish_allergens = []

    # Loop though all dishes
    for dish in dish_all:
        # To store allergens of each dish
        dish_allergen_list = []
        # Loop though ingredients of the dish
        for dish_ingred in dish.ingredient_id.all():
            # If there are allergic dishes, append all allergens to dish_allergen_list
            if dish_ingred.allergies_id.values():
                for allergen in dish_ingred.allergies_id.values():
                    dish_allergen_list.append(allergen['allergies_name'])
        # Append allergen info to dish_allergens list for use in filtering
        dish_allergens.append({
            "dish_id": dish.dish_id,
            "dish_allergen_list": dish_allergen_list
        })

        # loop though the categories of the dish and add it to dish_by_categories based on thecategory
        for dish_category in dish.category_id.values():
            dish_by_categories[dish_category['category_name']].append(dish)

    context = {
        # list of all dishes for use in menu.js
        "dish_all": list(dish_all.values()),

        # for rendering menu body
        "dish_by_categories": dish_by_categories,
        "dish_categories": dish_categories,

        # for rendering allergy filter section
        "dish_allergens": dish_allergens,
        "allergens": allergens,
    }

    # If customer presses "need help" button (POST request)
    if request.method == 'POST':
        table_id = request.POST.get('table_id')
        # Get the customer based on table_id and set need_help
        Customer.objects.filter(table_id=table_id).update(need_help=True)
        # for rendering "help is coming" in HTML
        context['help'] = True

    return render(request, 'restaurant/menu_public.html', context)


def payment(request, id):
    customer = Customer.objects.get(table_id=id)
    if request.method == 'POST':
        Payment.objects.create(
            order_id=id, payment_time=datetime.now(), payment_amount=customer.total_price)
        return redirect('restaurant:pay_success', id=id)
    else:
        template = loader.get_template('restaurant/payment.html')
        context = {
            'customer': customer,
            'payment': payment
        }
    return HttpResponse(template.render(context, request))


def payment_success(request, id):
    return HttpResponse(loader.get_template('restaurant/payment_success.html').render({"order_id": id}, request))


def is_waiter(user):
    return user.groups.filter(name='waiter').exists()


def is_kitchen(user):
    return user.groups.filter(name='kitchen').exists()


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username') # takes inputted username
            password = form.cleaned_data.get('password') # takes inputted password
            user = authenticate(username=username, password=password) # checks the details against the database
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                # change this value if you want to have the login page redirect somwhere.
                # if is_waiter(user):
                #     return redirect('restaurant:waiter_page')
                # else:
                return redirect('restaurant:dashboard')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="restaurant/login.html", context={"login_form": form})

def about(request):
    return render(request, "restaurant/aboutpage.html")

@ login_required # added 
def dashboard(request):
    print(" hi", request.user, request.user.groups.all())
    if is_waiter(request.user):
        print("waiter hi")
        return waiter_view(request)
    elif is_kitchen(request.user):
        return kitchen_view(request)
    return redirect('restaurant:login')


def updateOrder(request, pk):
    # form for updating the order clicked in the waiter dashboard.
    order = Order.objects.get(order_id=pk) # selects the order from the pk (primary key) clicked.
    form = OrderForm(instance=order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('restaurant:dashboard')

    context = {'form': form}
    return render(request, "restaurant/updateOrder.html", context=context)

def tableManager(request):
    # view for managing table designation.
    context = {
        # list of contexts for individual table objects.
        "One": Customer.objects.get(table_id=1),
        "Two": Customer.objects.get(table_id=2),
        "Three": Customer.objects.get(table_id=3),
        "Four": Customer.objects.get(table_id=4),
        "Five": Customer.objects.get(table_id=5),
        "Six": Customer.objects.get(table_id=6),
        "Seven": Customer.objects.get(table_id=7),
        "Eight": Customer.objects.get(table_id=8),
        "Nine": Customer.objects.get(table_id=9),
        "Ten": Customer.objects.get(table_id=10),
        "Eleven": Customer.objects.get(table_id=11),
        "Twelve": Customer.objects.get(table_id=12)
    }
    return render(request, 'restaurant/tableManager.html', context=context)

def updateTable(request, pk):
    # form for updating the customer data attached to each table currently.
    table = Customer.objects.get(table_id=pk) # selects the table from the pk (primary key) clicked.
    maxpersons = table.maxpersons
    form = TableForm(instance=table,maxpersons=maxpersons)
    if request.method == 'POST':
        form = TableForm(request.POST, instance=table,maxpersons=maxpersons)
        if form.is_valid():
            form.save()
            return redirect('restaurant:tableManager')
    
    context = {
        'form':form,   
    }
    return render(request, "restaurant/updateTable.html", context=context)


def cart(request):
    return render(request, 'restaurant/cart.html', {"dish_all": list(Dish.objects.all().order_by('dish_name').values())})


def orders(request, customer_id):
    customer = Customer.objects.get(table_id=customer_id)
    table_orders = Order.objects.filter(customer=customer)

    orders = []
    for order in table_orders:
        orders.append({
            "order_id": order.order_id,
            "order_time": order.order_time,
            "order_status": Status.objects.get(status_id=order.status_id_id),
            "dishes": order.dish_id.all()
        })

    context = {"orders": orders, "customer": customer}
    return render(request, 'restaurant/orders.html', context)

Oaxaca/restaurant/templates/restaurant/footer_public.html
<footer>
    <div id="oaxaca-footer" class="wrap">
        <p>
            © 2023 Oaxaca. All Rights Reserved.
            <br/>
            Built with Django in Python by Team 32.
        </p>
    </div>
</footer>

Oaxaca/restaurant/templates/restaurant/footer_staff.html
<footer>
    <div id="oaxaca-footer" class="wrap">
        <p>
            © 2023 Oaxaca. All Rights Reserved.
            <br/>
            Built with Django in Python by Team 32.
        </p>
    </div>
</footer>

Oaxaca/restaurant/templates/restaurant/header_kitchen.html
<header class="kitchen">
    <div id="oaxaca-menu-bar" class="wrap">
        <span id="oaxaca-logo"></span>
    </div>
    <div class="wrap">
        <nav id="oaxaca-menu-bar-nav">
            <a href="{% url 'restaurant:logout' %}">Log Off</a>
        </nav>
    </div>
</header>

Oaxaca/restaurant/templates/restaurant/menu_public.html
{% extends "restaurant/index.html" %}
{% load static %}
{% block content %}
    <section id="menu-categories" class="wrap">
        <nav id="menu-category-bar">
            {% if dish_categories %}
                {% for category in dish_categories %}
                    <a href="#{{ category.category_name }}"
                       class="menu-category font-medium">{{ category.category_name }}</a>
                {% endfor %}
            {% endif %}
        </nav>
    </section>
    <section id="menu-filters" class="wrap">
        {% if dish_by_categories %}
            <h3 class="heading-collapsible text-center">Show Filters</h3>
            <div class="margin-medium collapse">
                {% if allergens %}
                    <p class="font-medium margin-short">Allergens</p>
                    <div id="allergen-grid" class="menu-filter-grid">
                        {% for allergen in allergens %}
                            <label class="slide-toggle" for="{{ allergen.allergies_name }}">
                                <input class="slide-toggle-checkbox"
                                       id="{{ allergen.allergies_name }}"
                                       value="{{ allergen.allergies_name }}"
                                       type="checkbox"/>
                                <span class="slide-toggle-switch"></span>
                                <span class="slide-toggle-text">{{ allergen.allergies_name }} Free</span>
                            </label>
                        {% endfor %}
                    </div>
                {% endif %}
                <p class="font-medium margin-short">Menu Options</p>
                <div id="show-unavailable-grid" class="menu-filter-grid">
                    <label class="slide-toggle" for="unavailable">
                        <input class="slide-toggle-checkbox"
                               id="unavailable"
                               value="unavailable"
                               type="checkbox"/>
                        <span class="slide-toggle-switch"></span>
                        <span class="slide-toggle-text">Show Unavailable Dishes</span>
                    </label>
                </div>
                <div class="menu-filter-button-grid">
                    <button class="button button-medium button-block font-medium full-width"
                            onclick="applyFilters()">Apply</button>
                    <button class="button button-medium button-block font-medium full-width"
                            onclick="resetFilters()">
                        Reset All Filters
                    </button>
                </div>
            </div>
        {% endif %}
    </section>
    <section id="menu-list" class="wrap">
        {% if dish_by_categories %}
            {% for category, dishes in dish_by_categories.items %}
                <div id="{{ category }}" class="dish-cards-category">
                    <h2>{{ category }}</h2>
                    <div class="dish-cards-grid">
                        {% for dish in dishes %}
                            <div class="dish-card dish-{{ dish.dish_id }} {% if dish.dish_availability != True %}dish-unavailable{% endif %}">
                                <div class="dish-info">
                                    <div class="dish-info-row">
                                        <span class="dish-name font-semibold">{{ dish.dish_name }}</span>
                                    </div>
                                    <div class="dish-info-row">
                                        <span class="dish-price {% if dish.dish_price == 0 %}dish-free{% endif %} font-medium ">
                                            {% if dish.dish_price != 0 %}
                                                {{ dish.dish_price }}
                                            {% else %}
                                                Free
                                            {% endif %}
                                        </span>
                                    </div>
                                    <div class="dish-info-dropdown">
                                        <div class="dish-info-row hidden">
                                            <span class="dish-cal">{{ dish.dish_calories }}</span>
                                            <div class="dish-desc">
                                                Ingredients:
                                                {% for ingred in dish.ingredient_id.all %}
                                                    {% if ingred.allergies_id.all %}
                                                        <span class="dish-ingred dish-ingred-allergic">{{ ingred }}
                                                            (
                                                            {% for allergen in ingred.allergies_id.all %}{{ allergen.allergies_name }}{% endfor %}
                                                            )
                                                        </span>
                                                    {% else %}
                                                        <span class="dish-ingred">{{ ingred }}</span>
                                                    {% endif %}
                                                {% endfor %}
                                                {% for ingred, allergen in dish.dish_ingred_allergic.items %}
                                                    <span class="dish-ingred dish-ingred-allergic">{{ ingred }} ({{ allergen }})</span>
                                                {% endfor %}
                                                {% for ingred in dish.dish_ingred %}<span class="dish-ingred">{{ ingred }}</span>{% endfor %}
                                            </div>
                                        </div>
                                        <span class="dish-info-dropdown-btn button button-inline more-info"></span>
                                    </div>
                                    <div class="dish-info-row dish-order">
                                        {% if dish.dish_availability %}
                                            <button class="button button-block dish-count-btn dish-count-sub font-medium"></button>
                                            <input class="dish-count"
                                                   type="number"
                                                   min="1"
                                                   max="10"
                                                   maxlength="2"
                                                   value="1"/>
                                            <button class="button button-block dish-count-btn dish-count-add font-medium"></button>
                                            <button class="button button-medium button-block dish-add-btn font-medium">Add to cart</button>
                                        {% else %}
                                            <p>Currently Unavailable.</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div>
                                    <img class="dish-thumbnail"
                                         src="{% static 'images/dish/' %}{{ dish.dish_name }}.png"
                                         alt="{{ dish.dish_name }}"
                                         onerror="this.onerror=null;this.style.display='none';src='';this.class='';"/>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>Sorry, there are no dishes available.</p>
        {% endif %}
    </section>
    <div class="cart">
        <a href="{% url 'restaurant:cart' %}"
           class="button button-block block margin-short cart-button">Cart</a>
        <button onclick="popUpHelp()"
                class="button button-block block margin-short cart-button">Help</button>
    </div>
    {% include "restaurant/popup_help.html" %}
    {{ dish_all|json_script:"dish-all" }}
    {{ dish_allergens|json_script:"dish-allergens" }}
{% endblock content %}

Oaxaca/restaurant/templates/restaurant/menu_staff.html
{% extends "restaurant/index_staff.html" %}
{% block content %}
  <section class="wrap">
    <h1>Menu Management</h1>
    <div class="table full-width">
      <div class="table-row table-heading">
        <div class="table-cell table-heading">Item</div>
        <div class="table-cell table-heading text-center">Quantity</div>
        <div class="table-cell table-heading text-right">Price</div>
        <div class="table-cell table-heading text-center">Calories</div>
        <div class="table-cell table-heading">Availabile</div>
        <div class="table-cell table-heading">Actions</div>
      </div>
      {% for dish in dish_list %}
        <div class="table-row">
          <div class="table-cell">{{ dish.dish_name }}</div>
          <div class="table-cell text-center">{{ dish.dish_quantity }}</div>
          <div class="table-cell text-right price">{{ dish.dish_price }}</div>
          <div class="table-cell text-center">{{ dish.dish_calories }}</div>
          <div class="table-cell">
            <label class="slide-toggle disabled">
              <input class="slide-toggle-checkbox"
                     {% if dish.dish_availability %} checked{% endif %}
                     disabled
                     type="checkbox"/>
              <span class="slide-toggle-switch"></span>
            </label>
          </div>
          <div class="table-cell">
            <a href="{% url 'restaurant:staff-dish-details' dish.dish_id %}"
               class="button button-block">Edit</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock content %}

Oaxaca/restaurant/templates/restaurant/orders.html
{% extends 'restaurant/index.html' %}
{% load static %}
{% block content %}
    <section id="order-list" class="wrap">
        <h2>All orders for Table {{ customer.table_id }}</h2>
        {% if orders %}
            {% for order in orders %}
                <div id="order-{{ order.order_id }}" class="dish-cards-category">
                    <h2>Order ID {{ order.order_id }}: {{ order.order_status }}</h2>
                    <p>Order placed {{ order.order_time }}</p>
                    <div class="dish-cards-grid">
                        {% for dish in order.dishes %}
                            <div class="dish-card dish-{{ dish.dish_id }}">
                                <div class="dish-info">
                                    <div class="dish-info-row">
                                        <span class="dish-name font-semibold">{{ dish.dish_name }}</span>
                                    </div>
                                </div>
                                <div>
                                    <div class="dish-info-row">
                                        <span class="dish-price {% if dish.dish_price == 0 %}dish-free{% endif %} font-medium ">
                                            {% if dish.dish_price != 0 %}
                                                {{ dish.dish_price }}
                                            {% else %}
                                                Free
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div id="order-total" class="dish-cards-category">
                <p class="font-medium">
                    Total: <span class="dish-price">{{ customer.total_price }}</span>
                </p>
            </div>
        {% else %}
            <p>
                You have not ordered anything. How about some <a class="button button-inline" href="{% url 'restaurant:index' %}#Featured">Mom's Spaghetti</a>?
            </p>
        {% endif %}
    </section>
{% endblock content %}

Oaxaca/restaurant/templates/restaurant/popup_help.html
<div class="popup hidden" id="help-popup">
    <div class="popup-shade" onclick="popUpHide()"></div>
    <div class="popup-content popup-small text-center">
        <form id="help-form" action="{% url 'restaurant:index' %}" method="post">
            {% csrf_token %}
            <h3>Need assistance?</h3>
            <label for="table_id" class="margin-medium">Enter Your Table Number:</label>
            <br/>
            <input class="margin-medium"
                   id="help-table-number"
                   name="table_id"
                   type="number"
                   min="1"
                   max="99"
                   maxlength="2"
                   required/>
            <br/>
            <button type="submit" class="button button-block button-medium margin-medium">Get help</button>
            <input id="cart-data" name="cart-data" type="hidden"/>
        </form>
    </div>
</div>

Oaxaca/restaurant/templates/restaurant/updateOrder.html
{% extends "restaurant/index_staff.html" %}
{% block content %}

<style>
    *{color: #000}
</style>
<section class="wrap row">
    <div class="column middle">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" name="Submit">
            </form>
        </div>
    </div>
</section>

{% endblock content %}